export const SUPABASE_URL = 'https://fftrgptxfmokzwihvioj.supabase.co';
export const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmdHJncHR4Zm1va3p3aWh2aW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxODQyMzMsImV4cCI6MjA0OTc2MDIzM30.R_CjSId7aro_nuLEAzC2LCt6skAUhR_-CsHEuCviIgU';
